"use client";

import { useMemo, useState } from "react";
import { CalculatorHeader } from "../../components/CalculatorHeader";
import { calculateRoute, formatDuration, ROUTE_ASSUMPTIONS, ROUTE_CITIES } from "../../../lib/calculators/grand-voyage-route";

export default function GrandVoyageRoutePage() {
  const [route, setRoute] = useState<string[]>([ROUTE_CITIES[0], ROUTE_CITIES[1]]);
  const result = useMemo(() => { try { return calculateRoute(route); } catch { return null; } }, [route]);
  const updateCity = (index: number, city: string) => setRoute((current) => current.map((value, itemIndex) => itemIndex === index ? city : value));

  return <main className="calculator-shell calculator-wide"><CalculatorHeader eyebrow="Grand Voyage" title="Route calculator" description="Build a two-to-six-city round trip and compare every leg, travel time, profit, and profit per hour." /><section className="route-builder surface"><div className="route-controls"><div className="section-heading compact-heading"><h2>Route order</h2><button type="button" className="small-button" disabled={route.length >= 6} onClick={() => setRoute((current) => [...current, ROUTE_CITIES.find((city) => !current.includes(city)) ?? ROUTE_CITIES[0]])}>Add city</button></div>{route.map((city, index) => <div className="route-row" key={`${index}-${city}`}><span>{index + 1}</span><select aria-label={`City ${index + 1}`} value={city} onChange={(event) => updateCity(index, event.target.value)}>{ROUTE_CITIES.map((option) => <option disabled={option !== city && route.includes(option)} key={option}>{option}</option>)}</select>{route.length > 2 && <button type="button" aria-label={`Remove ${city}`} onClick={() => setRoute((current) => current.filter((_, itemIndex) => itemIndex !== index))}>×</button>}</div>)}</div>{result && <div className="route-results" aria-live="polite"><div className="metric-grid"><div><span>Travel time</span><strong>{formatDuration(result.totalTravelHours)}</strong></div><div><span>Total profit</span><strong>{result.totalProfit.toLocaleString()}</strong></div><div><span>Profit / hour</span><strong>{result.profitPerHour.toLocaleString(undefined, { maximumFractionDigits: 0 })}</strong></div></div><h3>{result.completeRoute.join(" → ")}</h3><div className="leg-list">{result.legs.map((leg) => <div key={`${leg.origin}-${leg.destination}`}><span>{leg.origin} → {leg.destination}</span><span>{formatDuration(leg.travelHours)} · {leg.profit >= 0 ? "+" : ""}{leg.profit.toLocaleString()}</span></div>)}</div></div>}</section><details className="assumption"><summary>Full-stat model assumptions</summary><ul>{ROUTE_ASSUMPTIONS.map((assumption) => <li key={assumption}>{assumption}</li>)}</ul><p>The calculator evaluates only the order you select; it does not optimize the route or check map access and ship range.</p></details></main>;
}
