/**
 * Which data files may be replaced from the site, and whether a payload is
 * allowed to stand in for one.
 *
 * Every file under `lib/data/` is registered, keyed by its own name, so a new
 * guide needs nothing added here beyond its file. What a payload has to look
 * like is read off the committed file itself — see `data-shape.ts` — rather
 * than written out per guide, which is how the check stays honest as the files
 * change.
 *
 * Generated by hand once and kept in step by `tests/guide-data.test.mjs`,
 * which fails if a file under `lib/data/` is missing from the list.
 */

import { fitsCommitted } from "./data-shape.ts";
import anecdotes from "../data/anecdotes.json" with { type: "json" };
import artworkLayouts from "../data/artwork-layouts.json" with { type: "json" };
import buildingLevels from "../data/building-levels.json" with { type: "json" };
import buildings from "../data/buildings.json" with { type: "json" };
import collectionLayouts from "../data/collection-layouts.json" with { type: "json" };
import collection from "../data/collection.json" with { type: "json" };
import cryptides from "../data/cryptides.json" with { type: "json" };
import eventWiki from "../data/event-wiki.json" with { type: "json" };
import goddessLeveling from "../data/goddess-leveling.json" with { type: "json" };
import goddessLoreDe from "../data/goddess-lore-de.json" with { type: "json" };
import goddessLoreFr from "../data/goddess-lore-fr.json" with { type: "json" };
import goddessSkins from "../data/goddess-skins.json" with { type: "json" };
import goddessTheater from "../data/goddess-theater.json" with { type: "json" };
import goddesses from "../data/goddesses.json" with { type: "json" };
import grandVoyageRoutes from "../data/grand-voyage-routes.json" with { type: "json" };
import grandVoyageShipwreckObservation from "../data/grand-voyage-shipwreck-observation.json" with { type: "json" };
import heroBaseValues from "../data/hero-base-values.json" with { type: "json" };
import heroLayouts from "../data/hero-layouts.json" with { type: "json" };
import heroLeveling from "../data/hero-leveling.json" with { type: "json" };
import heroLinking from "../data/hero-linking.json" with { type: "json" };
import heroLoreDe from "../data/hero-lore-de.json" with { type: "json" };
import heroLoreFr from "../data/hero-lore-fr.json" with { type: "json" };
import heroSkins from "../data/hero-skins.json" with { type: "json" };
import heroTiers from "../data/hero-tiers.json" with { type: "json" };
import heroes from "../data/heroes.json" with { type: "json" };
import museion from "../data/museion.json" with { type: "json" };
import paintings from "../data/paintings.json" with { type: "json" };
import serverAgeUnlocks from "../data/server-age-unlocks.json" with { type: "json" };
import theaterIncome from "../data/theater-income.json" with { type: "json" };
import tradeSets from "../data/trade-sets.json" with { type: "json" };

/** Every replaceable file, by the name it has on disk without the extension. */
export const DATA_FILES: Record<string, unknown> = {
  "anecdotes": anecdotes,
  "artwork-layouts": artworkLayouts,
  "building-levels": buildingLevels,
  "buildings": buildings,
  "collection-layouts": collectionLayouts,
  "collection": collection,
  "cryptides": cryptides,
  "event-wiki": eventWiki,
  "goddess-leveling": goddessLeveling,
  "goddess-lore-de": goddessLoreDe,
  "goddess-lore-fr": goddessLoreFr,
  "goddess-skins": goddessSkins,
  "goddess-theater": goddessTheater,
  "goddesses": goddesses,
  "grand-voyage-routes": grandVoyageRoutes,
  "grand-voyage-shipwreck-observation": grandVoyageShipwreckObservation,
  "hero-base-values": heroBaseValues,
  "hero-layouts": heroLayouts,
  "hero-leveling": heroLeveling,
  "hero-linking": heroLinking,
  "hero-lore-de": heroLoreDe,
  "hero-lore-fr": heroLoreFr,
  "hero-skins": heroSkins,
  "hero-tiers": heroTiers,
  "heroes": heroes,
  "museion": museion,
  "paintings": paintings,
  "server-age-unlocks": serverAgeUnlocks,
  "theater-income": theaterIncome,
  "trade-sets": tradeSets,
};

export type DataFileName = keyof typeof DATA_FILES;

export const DATA_FILE_NAMES = Object.keys(DATA_FILES);

export function isDataFileName(value: string): boolean {
  return Object.hasOwn(DATA_FILES, value);
}

/** The file as the build carries it. */
export function committedData(name: string): unknown {
  return DATA_FILES[name];
}

/**
 * The data a page should use: the payload when it looks like the file it
 * replaces, otherwise the file. Never a mixture — half a roster is worse than
 * the old one.
 */
export function resolveData(name: string, payload: unknown): unknown {
  const committed = DATA_FILES[name];
  if (committed === undefined || payload == null) return committed;
  return fitsCommitted(committed, payload) ? payload : committed;
}

/** Whether a payload would be used, for an editor to say so before saving. */
export function dataFits(name: string, payload: unknown): boolean {
  const committed = DATA_FILES[name];
  return committed !== undefined && fitsCommitted(committed, payload);
}
